### ISSUE TITLE
Change SVG DPI from 96 to 75.

### ISSUE THREAD

**Issue by AndrewBelt** [VCVRack/Rack#337]
Currently Rack SVG panels and components follow the 380px height standard. I will change this to the 5.06" height standard to match physical Eurorack sizes. In order to minimize migration pains, I will change the DPI of loaded SVG files from 96 to 75 so that existing pixel values will correspond to the same positions at the new DPI (since 5.06" * 75 DPI = 379.5px, which is close enough).

### TODO
- [x] Change DPI
- [x] Add `in2px` and `mm2px` functions for convenience
- [x] ~~Provide script on Gist for developers to convert their existing panels from 380px-height to 5.06"-height automatically with the command line~~ Use the below instructions. If someone prefers, you may be able to automate this with [libRSVG](https://wiki.gnome.org/Projects/LibRsvg).

>Developers must open the SVG files in Inkscape (others may work but not tested), open Document Properties (Shift+Ctrl+D), under the Orientation section set Units to "px", and Save.

- [x] Convert all Component Library graphics to 5.06" height

- [x] Convert all VCV plugins' panels to 5.06" height

**Comment by antoniograzioli** [comment]
does this apply to panels only or also knobs, buttons and so on?

**Comment by AndrewBelt** [comment]
Yes, anything that is an SVG file.

**Comment by fenykep** [comment]
How can I update the fixed SVGs if I edit them for the other devs?

**Comment by AndrewBelt** [comment]
I don't understand. Explain your scenerio a bit?

**Comment by AndrewBelt** [comment]
Tasks finished
